### ISSUE TITLE
possibility to disable logfile.max_bytes

### ISSUE THREAD

**Issue by bmaeser** [backup/backup-features#31]
hi,

there should be the possibility to disable `logfile.max_bytes`, e.g. by setting it to `0`.

reason is, i would like to log to /var/log/backup, and let logrotate handle rotation.
this is much more "unixy" on a production server.

at the moment i work arround this, by setting it to a very large size - like 500 MB

**Comment by tombruijn** [comment]
Thanks for the suggestion @bmaeser! However, personally I don't like using magic numbers. 0 would mean to me an empty log file at all times.

So why not be more descriptive and use `logfile.max_bytes = Float::INFINITY` instead? This is supported as far as I can see. `BigDecimal::INFINITY` also seems to work

Would this solve your problem?

**Comment by bmaeser** [comment]
Oh yes, that will work just fine, thanks a lot! I did not know about `Float::INFINITY`, i don't speak any ruby.

BTW: i think this should be mentioned in the documentation.
