### ISSUE TITLE
Allow `#keep` to accept Date object as well as Fixnum

### ISSUE THREAD

**Issue by patcon** [backup/backup-features#33]
This would mainly avoid situations where backups unexpectedly fall short due to manually running cron scripts. ie. if you manually ran against a model that triggered the monthly builds on that day, you might run 12 tests and unexpectedly lose 12 months of monthly backups. Allowing backups to expire by date makes this a non-issue, as you just consume extra storage (which is probably cheaper :)

**Comment by tombruijn** [comment]
Hi @patcon, thanks for the idea!

Just to see if it could easily be done I added in about 20 minutes. It's not tested though as I'd have to look where this is tested. Maybe I'll get back to [the PR](https://github.com/backup/backup/pull/701) in a little while

This is what you had in mind, right?

Edit: actually add the link: https://github.com/backup/backup/pull/701

**Comment by patcon** [comment]
Wow! Thanks Tom! Was expecting to do this myself, but this looks perfect

I'll aim to test it out for awhile in my testing environment

**Comment by tombruijn** [comment]
Added in https://github.com/backup/backup/pull/701

**Comment by patcon** [comment]
Thanks so much tom!

**Comment by tombruijn** [comment]
This was released today in backup 4.2.1

**Comment by patcon** [comment]
:+1:
